spring:
  application:
    name: monkeyquest
  sql:
    init:
      data-locations: classpath:data.psql
      mode: always   # Ensure the script runs on startup
  jpa:
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://ep-silent-fire-a8irz4wb-pooler.eastus2.azure.neon.tech/monkeyquest
    #    url: jdbc:postgresql://ep-soft-recipe-a189x52v.ap-southeast-1.aws.neon.tech/test?sslmode=require
    username: neondb_owner
    password: npg_VqUgStY97NRu
    driver-class-name: org.postgresql.Driver
server:
  port: 5455
urls:
  baseurl: http://localhost
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

## Allows Hibernate to generate SQL optimized for a particular DBMS
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect